+access+rw
+loadpli1=/cadtools/synopsys/verdi/I-2014.03/share/PLI/IUS/LINUX/boot/debpli.so:novas_pli_boot
-timescale 1ns/10ps
+incdir+../../outdir/nv_small/spec/defs
+incdir+../../outdir/nv_small/vmod/include
+incdir+../../outdir/nv_small/vmod/vlibs
+incdir+../../itri_tb
+define+SYNTHESIS
+define+NV_SMALL_64
+define+PRIMARY_MEMIF_WIDTH_64
-DNVDLA_PRIMARY_MEMIF_WIDTH=64

../../outdir/nv_small/vmod/nvdla/top/NV_nvdla_apb.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_a.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_o.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_c.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_p.v
../../outdir/nv_small/vmod/nvdla/top/NV_NVDLA_partition_m.v

../../outdir/nv_small/vmod/nvdla/apb2csb/NV_NVDLA_apb2csb.v

../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_CALC_int8.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_assembly_buffer.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_assembly_ctrl.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_calculator.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_delivery_buffer.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_delivery_ctrl.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_dual_reg.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_regfile.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_single_reg.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_CACC_slcg.v
../../outdir/nv_small/vmod/nvdla/cacc/NV_NVDLA_cacc.v

../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_core_reset.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_reset.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_sync3d.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_sync3d_s.v
../../outdir/nv_small/vmod/nvdla/car/NV_NVDLA_sync3d_c.v

../../outdir/nv_small/vmod/nvdla/cbuf/NV_NVDLA_cbuf.v

../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_CVT_cell.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_DC_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_ctrl.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_pack.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg2pack_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_fifo.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_cvt.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_dc.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_dma_mux.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_dual_reg.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_img.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_regfile.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_shared_buffer.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_single_reg.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_slcg.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_status.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_CDMA_wt.v
../../outdir/nv_small/vmod/nvdla/cdma/NV_NVDLA_cdma.v

../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_INTP_unit.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_CTRL_unit.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_ctrl.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_MUL_unit.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_bufferin_tp1.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_cvtin.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_cvtout.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_intp.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_lut.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_mul.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_nan.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_sum.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_DP_syncfifo.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_dual.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_single.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_cq.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_eg.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_ig.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_reg.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_REG_dual.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_REG_single.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_dp.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_rdma.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_reg.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_slcg.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_CDP_wdma.v
../../outdir/nv_small/vmod/nvdla/cdp/NV_NVDLA_cdp.v
../../outdir/nv_small/vmod/nvdla/cdp/int_sum_block_tp1.v

../../outdir/nv_small/vmod/nvdla/cfgrom/NV_NVDLA_cfgrom.v
../../outdir/nv_small/vmod/nvdla/cfgrom/NV_NVDLA_CFGROM_rom.v

../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_active.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_cfg.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_mac.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_in.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_out.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_slcg.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_REG_dual.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_REG_single.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_core.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_CMAC_reg.v
../../outdir/nv_small/vmod/nvdla/cmac/NV_NVDLA_cmac.v

../../outdir/nv_small/vmod/nvdla/csb_master/NV_NVDLA_CSB_MASTER_csb2falcon_fifo.v
../../outdir/nv_small/vmod/nvdla/csb_master/NV_NVDLA_CSB_MASTER_falcon2csb_fifo.v
../../outdir/nv_small/vmod/nvdla/csb_master/NV_NVDLA_csb_master.v

../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_SG_dat_fifo.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_SG_wt_fifo.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_WL_dec.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_dl.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_dual_reg.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_regfile.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_sg.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_single_reg.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_slcg.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_CSC_wl.v
../../outdir/nv_small/vmod/nvdla/csc/NV_NVDLA_csc.v

../../outdir/nv_small/vmod/nvdla/glb/NV_NVDLA_GLB_CSB_reg.v
../../outdir/nv_small/vmod/nvdla/glb/NV_NVDLA_GLB_csb.v
../../outdir/nv_small/vmod/nvdla/glb/NV_NVDLA_GLB_ic.v
../../outdir/nv_small/vmod/nvdla/glb/NV_NVDLA_glb.v

../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_DMAIF_rdreq.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_DMAIF_rdrsp.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_DMAIF_wr.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_MCIF_CSB_reg.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_MCIF_csb.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_arb.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_bpt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_cvt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_IG_spt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_cq.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_eg.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_READ_ig.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_arb.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_bpt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_cvt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_IG_spt.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_cq.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_eg.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_WRITE_ig.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_read.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_DRAM_write.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_NOCIF_dram.v
../../outdir/nv_small/vmod/nvdla/nocif/NV_NVDLA_XXIF_libs.v

../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_cal1d.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_cal2d.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_preproc.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_unit1d.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_dual.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_single.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_cq.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_eg.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_ig.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_reg.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_REG_dual.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_REG_single.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_WDMA_cmd.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_WDMA_dat.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_core.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_nan.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_rdma.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_reg.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_slcg.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_PDP_wdma.v
../../outdir/nv_small/vmod/nvdla/pdp/NV_NVDLA_pdp.v

../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_cq.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_lat_fifo.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_pack.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_unpack.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_C_int.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_alu.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_mul.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_relu.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_X_int_trt.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_c.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_prelu.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_relu.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_sync2data.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_x1_int.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_HLS_x2_int.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_cmd.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_din.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_dout.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_cq.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_eg.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_ig.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_cq.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_lat_fifo.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_EG_ro.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_dual.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_single.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_dmaif.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_eg.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_ig.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_pack.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_reg.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_unpack.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_REG_dual.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_REG_single.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_in.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_out.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_cmd.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_dat.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_gate.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_intr.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_brdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_cmux.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_core.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_mrdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_nrdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_rdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_reg.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_SDP_wdma.v
../../outdir/nv_small/vmod/nvdla/sdp/NV_NVDLA_sdp.v



../../outdir/nv_small/vmod/vlibs/AN2D4PO4.v
../../outdir/nv_small/vmod/vlibs/CKLNQD12.v
../../outdir/nv_small/vmod/vlibs/CKLNQD12PO4.v
../../outdir/nv_small/vmod/vlibs/HLS_cdp_icvt.v
../../outdir/nv_small/vmod/vlibs/HLS_cdp_ocvt.v
../../outdir/nv_small/vmod/vlibs/LNQD1PO4.v
../../outdir/nv_small/vmod/vlibs/MUX2D4.v
../../outdir/nv_small/vmod/vlibs/MUX2HDD2.v
../../outdir/nv_small/vmod/vlibs/NV_BLKBOX_BUFFER.v
../../outdir/nv_small/vmod/vlibs/NV_BLKBOX_SINK.v
../../outdir/nv_small/vmod/vlibs/NV_BLKBOX_SRC0.v
../../outdir/nv_small/vmod/vlibs/NV_BLKBOX_SRC0_X.v
../../outdir/nv_small/vmod/vlibs/NV_CLK_gate_power.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_saturate.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_shiftleftsu.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_shiftrightsatsu.v
../../outdir/nv_small/vmod/vlibs/NV_NVDLA_HLS_shiftrightsu.v
../../outdir/nv_small/vmod/vlibs/OR2D1.v
../../outdir/nv_small/vmod/vlibs/SDFCNQD1.v
../../outdir/nv_small/vmod/vlibs/SDFQD1.v
../../outdir/nv_small/vmod/vlibs/SDFSNQD1.v
../../outdir/nv_small/vmod/vlibs/ScanShareSel_JTAG_reg_ext_cg.v
../../outdir/nv_small/vmod/vlibs/oneHotClk_async_read_clock.v
../../outdir/nv_small/vmod/vlibs/oneHotClk_async_write_clock.v
../../outdir/nv_small/vmod/vlibs/p_SDFCNQD1PO4.v
../../outdir/nv_small/vmod/vlibs/p_SSYNC2DO_C_PP.v
../../outdir/nv_small/vmod/vlibs/p_SSYNC3DO.v
../../outdir/nv_small/vmod/vlibs/p_SSYNC3DO_C_PPP.v
../../outdir/nv_small/vmod/vlibs/p_SSYNC3DO_S_PPP.v
../../outdir/nv_small/vmod/vlibs/p_STRICTSYNC3DOTM_C_PPP.v
../../outdir/nv_small/vmod/vlibs/sync3d.v
../../outdir/nv_small/vmod/vlibs/sync2d_c_pp.v
../../outdir/nv_small/vmod/vlibs/sync3d_c_ppp.v
../../outdir/nv_small/vmod/vlibs/sync3d_s_ppp.v
../../outdir/nv_small/vmod/vlibs/sync_reset.v
../../outdir/nv_small/vmod/vlibs/nv_assert_no_x.vlib

../../small_rams/nv_ram_rws_128x18.v
../../small_rams/nv_ram_rws_16x256.v
../../small_rams/nv_ram_rws_16x272.v
../../small_rams/nv_ram_rws_16x64.v
../../small_rams/nv_ram_rws_256x3.v
../../small_rams/nv_ram_rws_256x64.v
../../small_rams/nv_ram_rws_256x7.v
../../small_rams/nv_ram_rwsp_128x11.v
../../small_rams/nv_ram_rwsp_128x6.v
../../small_rams/nv_ram_rwsp_160x16.v
../../small_rams/nv_ram_rwsp_160x65.v
../../small_rams/nv_ram_rwsp_61x65.v
../../small_rams/nv_ram_rwsp_80x14.v
../../small_rams/nv_ram_rwsp_80x65.v
../../small_rams/nv_ram_rwsp_8x65.v
../../small_rams/nv_ram_rwst_256x8.v
../../small_rams/nv_ram_rwsthp_19x4.v
../../small_rams/nv_ram_rwsthp_60x21.v
../../small_rams/nv_ram_rwsthp_80x15.v
../../small_rams/nv_ram_rwsthp_80x9.v

../../itri_tb/test.v
../../itri_tb/axi_mem.v
../../itri_tb/axi_slave_fast.v
../../itri_tb/ext_mem.v
../../itri_tb/sync_axi_mem.v
../../itri_tb/sequencer_apb.v

../../itri_tb/parse_cfg.c
../../itri_tb/check_result.c
