SYSC_MODULE = rm_convertor_dpi
V = @
CXX = /home/kcchang/gcc-4.8.3/DEST/bin/g++
CXXFLAGS =  -I/home/kcchang/nvdla_master/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/include -I/home/kcchang/nvdla_master/hw/cmod/include -I/home/kcchang/nvdla_master/hw/cmod/include/nvdla_ness_header -I/home/kcchang/nvdla_master/hw/outdir/nv_small/spec/defs -pipe -DVCSMX -DVCSSYSTEMC=1  -MMD -m64 -fPIC
INCLUDES = \
	-I/home/kcchang/nvdla_master/hw/outdir/nv_small/verif/vip/reference_model/rm_nvdla_top \
	-I/home/kcchang/nvdla_master/hw/outdir/nv_small/verif/testbench/trace_player/csrc/sysc/include \
	-I/cadtools/synopsys/vcs_mx/L-2016.06-SP2-6/include/systemc23 \
	-I/cadtools/synopsys/vcs_mx/L-2016.06-SP2-6/include/systemc23 \
	-Iinclude \
	-I$(VCS_HOME)/lib \
	-I$(VCS_HOME)/include \
	-I$(VCS_HOME)/include/cosim/bf \
	-I$(SNPS_SIM_OVRD)/include \
	-I/home/kcchang/nvdla_master/hw/outdir/nv_small/verif/testbench/trace_player

OBJS = rm_convertor_dpi.o

module-rm_convertor_dpi:	$(OBJS)
rm_convertor_dpi.o:
	@rm -f rm_convertor_dpi.o
	@$(MAKE) -f Makefile_shared clean
	$(V) $(CXX) $(INCLUDES) $(CXXFLAGS) -c /home/kcchang/nvdla_master/hw/outdir/nv_small/verif/vip/reference_model/rm_nvdla_top/rm_convertor_dpi.cpp -o $@ 

clean:
	$(V) rm -f rm_convertor_dpi.o

-include rm_convertor_dpi.d

